// ============================================================
// AirwayLab — Forum-Formatted Export
// Generates copy-paste text for ApneaBoard, r/SleepApnea, etc.
// ============================================================

import type { NightResult } from './types';
import { getTrafficLight } from './thresholds';
import { getStoredThresholds } from './threshold-overrides';

function light(val: number, key: string): string {
  const THRESHOLDS = getStoredThresholds();
  const threshold = THRESHOLDS[key];
  if (!threshold) return '';
  const l = getTrafficLight(val, threshold);
  return l === 'good' ? '✅' : l === 'warn' ? '⚠️' : '🔴';
}

function fmt(n: number, dp = 1): string {
  return n.toFixed(dp);
}

function fmtHrs(h: number): string {
  const hrs = Math.floor(h);
  const mins = Math.round((h - hrs) * 60);
  return `${hrs}h ${mins}m`;
}

/**
 * Generate a markdown-style forum post summarising one night.
 */
export function exportForumSingleNight(n: NightResult): string {
  const lines: string[] = [];

  lines.push(`**AirwayLab Analysis — ${n.dateStr}**`);
  lines.push('');
  lines.push(`Machine: ${n.settings.deviceModel} | Mode: ${n.settings.papMode}`);
  if (n.settings.epap > 0) {
    lines.push(`Pressures: EPAP ${n.settings.epap} / IPAP ${n.settings.ipap} cmH₂O (PS ${n.settings.pressureSupport})`);
  }
  lines.push(`Duration: ${fmtHrs(n.durationHours)} (${n.sessionCount} session${n.sessionCount !== 1 ? 's' : ''})`);
  lines.push('');

  // Glasgow
  lines.push('**Flow Limitation (Glasgow Index)**');
  lines.push(`Overall: ${fmt(n.glasgow.overall)} ${light(n.glasgow.overall, 'glasgowOverall')}`);

  const comps = [
    ['Skew', n.glasgow.skew],
    ['Spike', n.glasgow.spike],
    ['Flat Top', n.glasgow.flatTop],
    ['Top Heavy', n.glasgow.topHeavy],
    ['Multi-Peak', n.glasgow.multiPeak],
    ['No Pause', n.glasgow.noPause],
    ['Insp Rate', n.glasgow.inspirRate],
    ['Multi-Breath', n.glasgow.multiBreath],
    ['Var Amp', n.glasgow.variableAmp],
  ] as const;
  lines.push(`Components: ${comps.map(([name, val]) => `${name} ${fmt(val, 2)}`).join(' | ')}`);
  lines.push('');

  // WAT
  lines.push('**Ventilation Analysis (WAT)**');
  lines.push(`FL Score: ${fmt(n.wat.flScore)}% ${light(n.wat.flScore, 'watFL')} | Regularity: ${Math.round(n.wat.regularityScore)}% ${light(n.wat.regularityScore, 'watRegularity')} | Periodicity: ${fmt(n.wat.periodicityIndex)}% ${light(n.wat.periodicityIndex, 'watPeriodicity')}`);
  lines.push(`Est. Arousal Index: ${fmt(n.wat.estimatedArousalIndex)}/hr ${light(n.wat.estimatedArousalIndex, 'watEAI')}`);
  lines.push('');

  // NED
  lines.push('**Breath Analysis (NED)**');
  lines.push(`NED Mean: ${fmt(n.ned.nedMean)}% ${light(n.ned.nedMean, 'nedMean')} | Combined FL: ${Math.round(n.ned.combinedFLPct)}% ${light(n.ned.combinedFLPct, 'combinedFL')} | RERA Index: ${fmt(n.ned.reraIndex)}/hr ${light(n.ned.reraIndex, 'reraIndex')}`);
  lines.push(`H1 NED: ${fmt(n.ned.h1NedMean)}% | H2 NED: ${fmt(n.ned.h2NedMean)}%`);
  lines.push('');

  // Oximetry
  if (n.oximetry) {
    const ox = n.oximetry;
    lines.push('**Oximetry**');
    lines.push(`ODI-3: ${fmt(ox.odi3)}/hr ${light(ox.odi3, 'odi3')} | ODI-4: ${fmt(ox.odi4)}/hr ${light(ox.odi4, 'odi4')}`);
    lines.push(`T<90%: ${fmt(ox.tBelow90)} min ${light(ox.tBelow90, 'tBelow90')} | SpO₂ Mean: ${fmt(ox.spo2Mean)}% ${light(ox.spo2Mean, 'spo2Mean')}`);
    lines.push(`HR Clin 10: ${fmt(ox.hrClin10)}/hr ${light(ox.hrClin10, 'hrClin10')} | Coupled 3/10: ${fmt(ox.coupled3_10)}/hr`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [AirwayLab](https://airwaylab.app) — free, open-source airway analysis. Your data never leaves your browser. [⭐ Star on GitHub](https://github.com/airwaylab-app/airwaylab)*');
  lines.push('*Not medical advice — discuss results with your clinician.*');

  return lines.join('\n');
}

/**
 * Generate a multi-night summary table for forum posts.
 */
export function exportForumMultiNight(nights: NightResult[]): string {
  const lines: string[] = [];
  const sorted = [...nights].sort((a, b) => a.dateStr.localeCompare(b.dateStr));

  lines.push(`**AirwayLab Summary — ${sorted.length} Nights**`);
  lines.push(`(${sorted[0].dateStr} to ${sorted[sorted.length - 1].dateStr})`);
  lines.push('');
  lines.push(`Machine: ${sorted[0].settings.deviceModel} | Mode: ${sorted[0].settings.papMode}`);
  lines.push('');

  // Table header
  lines.push('| Date | Duration | Glasgow | FL Score | NED Mean | RERA/hr | EAI | Regularity |');
  lines.push('|------|----------|---------|----------|----------|---------|-----|------------|');

  for (const n of sorted) {
    lines.push(
      `| ${n.dateStr} | ${fmtHrs(n.durationHours)} | ${fmt(n.glasgow.overall)} ${light(n.glasgow.overall, 'glasgowOverall')} | ${fmt(n.wat.flScore)}% | ${fmt(n.ned.nedMean)}% | ${fmt(n.ned.reraIndex)} | ${fmt(n.wat.estimatedArousalIndex)} ${light(n.wat.estimatedArousalIndex, 'watEAI')} | ${Math.round(n.wat.regularityScore)}% |`
    );
  }

  // Averages row
  const avg = (fn: (n: NightResult) => number) =>
    sorted.reduce((sum, n) => sum + fn(n), 0) / sorted.length;

  lines.push(
    `| **Average** | | **${fmt(avg((n) => n.glasgow.overall))}** | **${fmt(avg((n) => n.wat.flScore))}%** | **${fmt(avg((n) => n.ned.nedMean))}%** | **${fmt(avg((n) => n.ned.reraIndex))}** | **${fmt(avg((n) => n.wat.estimatedArousalIndex))}** | **${Math.round(avg((n) => n.wat.regularityScore))}%** |`
  );

  lines.push('');

  // Oximetry table if any night has it
  const oxNights = sorted.filter((n) => n.oximetry);
  if (oxNights.length > 0) {
    lines.push('**Oximetry**');
    lines.push('| Date | ODI-3 | T<90% | SpO₂ Mean | HR Clin 10 |');
    lines.push('|------|-------|-------|-----------|------------|');
    for (const n of oxNights) {
      const ox = n.oximetry!;
      lines.push(
        `| ${n.dateStr} | ${fmt(ox.odi3)}/hr ${light(ox.odi3, 'odi3')} | ${fmt(ox.tBelow90)} min | ${fmt(ox.spo2Mean)}% | ${fmt(ox.hrClin10)}/hr |`
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [AirwayLab](https://airwaylab.app) — free, open-source airway analysis. Your data never leaves your browser. [⭐ Star on GitHub](https://github.com/airwaylab-app/airwaylab)*');
  lines.push('*Not medical advice — discuss results with your clinician.*');

  return lines.join('\n');
}
